name: Build packages (on push)

# This workflow runs when any of the following occur:
# - On push

on:
    push:
        paths-ignore:
        - '**/*.md'

jobs:
    call-test-workflow:
        runs-on: ubuntu-24.04

    call-build-workflow:
        uses: ./.github/workflows/5_builderpackage_reporting.yml
        secrets: inherit