name: CI

# This workflow runs when any of the following occur:
# - On any changes

on:
    push:


jobs:
  call-test-workflow:
    runs-on: ubuntu-24.04
    
    steps:
    
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Gradle check
        run: ./gradlew check  
