name: Link Checker
on:
  schedule:
    - cron: "00 8 * * 5"

jobs:
  linkchecker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --accept=200,403,429  "./**/*.md" "./**/*.txt" --exclude-all-private --insecure
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
